create_library:
	sudo mysql -u root -p < ./create_and_enter_library.sql
remove_library:
	sudo mysql -u root -p library -t < ./remove_library.sql
create_tables:
	sudo mysql -u root -p library -t < ./create_tables.sql
remove_tables:
	sudo mysql -u root -p library -t < ./remove_all_tables.sql
show_tables:
	sudo mysql -u root -p library -t < ./show_table_names.sql
triggers:
	sudo mysql -u root -p library -t < ./triggers.sql
all_tables:
	sudo mysql -u root -p library -t < ./show_all_tables.sql
show_triggers:
	sudo mysql -u root -p library -t < ./show_triggers.sql
branch_insert:
	sudo mysql -u root -p library -t < ./insert_in_branch.sql
customer_insert:
	sudo mysql -u root -p library -t < ./insert_in_customer.sql
customer_subscription_insert:
	sudo mysql -u root -p library -t < ./insert_in_customer_subscription.sql
author_insert:
	sudo mysql -u root -p library -t < ./insert_in_author.sql
books_insert:
	sudo mysql -u root -p library -t < ./insert_in_books.sql
borrowed_insert:
	sudo mysql -u root -p library -t < ./insert_in_borrowed.sql
